import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { app } from "electron";

const here = dirname(fileURLToPath(import.meta.url));

/** Absolute path to the built desktop package root. */
export const desktopRoot = resolve(here, "..");

const repositoryRoot = resolve(desktopRoot, "..", "..");

const packagedAssetsRoot = app.isPackaged && process.resourcesPath
  ? resolve(process.resourcesPath, "assets")
  : resolve(repositoryRoot, "assets");

/** Absolute path to the desktop shell icon asset used by Electron windows. */
export const desktopWindowIcon = resolve(
  packagedAssetsRoot,
  process.platform === "win32" ? "kaze-app-icon.ico" : "kaze-app-icon.png",
);

/** Absolute path to the icon used by Electron's native drag preview. */
export const desktopDragFileIcon = resolve(packagedAssetsRoot, "drag-file-icon.png");

/** Absolute path to the renderer HTML generated by Vite. */
export const rendererDist = resolve(desktopRoot, "renderer-dist", "index.html");

/** Absolute path to the dedicated desktop-pet renderer entry generated by Vite. */
export const rendererPetDist = resolve(desktopRoot, "renderer-dist", "pet.html");

/** Absolute path to the hidden microphone capture renderer entry generated by Vite. */
export const rendererVoiceDist = resolve(desktopRoot, "renderer-dist", "voice.html");

/** Vite dev server URL used by the desktop shell during renderer development. */
export const rendererDevServerUrl = process.env.HASAKI_RENDERER_DEV_SERVER_URL;

/** Absolute path to the compiled preload script loaded by Electron. */
export const preloadScript = resolve(here, "preload.js");
